### description




- reward : `-1`
- action : random policy (up : `0.25`, down : `0.25`, left : `0.25`, right : `0.25`)
- state : `wall`은 `100`으로 표현하였으며, 내부에 있는 좌표를 state로 표현
- value function table : 초기 value function은 모두 0으로 설정

| . | . | . | . | . | . |
|---|:---:|---:|---:|---:|---:|
| 100 | 100 | 100 | 100 | 100 | 100 |
| 100 | start | 0 | 0 | 0 | 100 |
| 100 | 0 | 0 | 0 | 0 | 100 |
| 100 | 0 | 0 | 0 | 0 | 100 |
| 100 | 0 | 0 | 0 | finish | 100 |
| 100 | 100 | 100 | 100 | 100 | 100 |

In [223]:
from itertools import product
import numpy as np

reward = -1

# action table
# actions = np.array([0.25, 0.25, 0.25, 0.25])
actions = {'up': 1/4, 'down':1/4, 'left':1/4, 'right':1/4}

print('1 : random policy table with 1/4')
print(actions)
print('\n')

# small grid에 대한 value table 생성

value_table = np.array([[100, 100, 100, 100, 100, 100],
                        [100, 0.0, 0.0, 0.0, 0.0, 100],
                        [100, 0.0, 0.0, 0.0, 0.0, 100],
                        [100, 0.0, 0.0, 0.0, 0.0, 100],
                        [100, 0.0, 0.0, 0.0, 0.0, 100],
                        [100, 100, 100, 100, 100, 100]])

print('2 : Initialized value table with 0')
print(value_table)
print('\n')

# small grid의 좌표 생성
print("3 : Index of value table")
size = 4
size = np.arange(1, size+1)
indexs = list(product(size, size))
print(indexs)

1 : random policy table with 1/4
{'up': 0.25, 'down': 0.25, 'left': 0.25, 'right': 0.25}


2 : Initialized value table with 0
[[100. 100. 100. 100. 100. 100.]
 [100.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0. 100.]
 [100.   0.   0.   0.   0. 100.]
 [100. 100. 100. 100. 100. 100.]]


3 : Index of value table
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 1), (2, 2), (2, 3), (2, 4), (3, 1), (3, 2), (3, 3), (3, 4), (4, 1), (4, 2), (4, 3), (4, 4)]


## function 

In [224]:
# epoch에 따른 value function 결과 출력 함수

def small_grid_world_value_function(epoch):
    '''
    args : epoch (k)로 update 수
    output : value function table
    '''
    
    # small grid의 value table 생성
    value_table = np.array([[100, 100, 100, 100, 100, 100],
                            [100, 0.0, 0.0, 0.0, 0.0, 100],
                            [100, 0.0, 0.0, 0.0, 0.0, 100],
                            [100, 0.0, 0.0, 0.0, 0.0, 100],
                            [100, 0.0, 0.0, 0.0, 0.0, 100],
                            [100, 100, 100, 100, 100, 100]])           
    
    for k in range(epoch): 
        
        temp_value_table = value_table.copy()

        for index in indexs:

            # 시작점 idnex = (1,1) 및 종료점 index = (4,4) 는 update skip
            if ((index[0] == 1) and (index[1] == 1)) or ((index[0] == 4) and (index[1] == 4)):
                continue

            # (1,2) .. (4,3) 순차적으로 업데이트하기 위해 (x, y) index 추출
            temp_x = index[0]
            temp_y = index[1]

            # s(x, y) 기준 action(up/down/left/right)에 따른 value_function(s'(x', y'), a) 값 참조
            temp_up_value = value_table[temp_x-1][temp_y]
            temp_down_value = value_table[temp_x+1][temp_y]
            temp_left_value = value_table[temp_x][temp_y-1]
            temp_right_value = value_table[temp_x][temp_y+1]

            # 위 action에서 벽에 부딪치는 경우 value_function(s'(x', y'), a) = value_function(s(x, y))
            if temp_up_value == 100:
                temp_up_value =  value_table[temp_x][temp_y]

            if temp_down_value == 100:
                temp_down_value =  value_table[temp_x][temp_y]

            if temp_left_value == 100:
                temp_left_value =  value_table[temp_x][temp_y]

            if temp_right_value == 100:
                temp_right_value =  value_table[temp_x][temp_y]              


            temp_value = actions['up']*(reward+temp_up_value)+actions['down']*(reward+temp_down_value)+actions['left']*(reward+temp_left_value)+actions['right']*(reward+temp_right_value)
            temp_value = np.round(temp_value, 3)
            #print(temp_value)
            temp_value_table[temp_x][temp_y] = temp_value

        value_table = temp_value_table.copy()
        
    return value_table

### output

In [215]:
# k = 0 에 따른 value function update
small_grid_world_value_function(epoch = 0)

array([[100., 100., 100., 100., 100., 100.],
       [100.,   0.,   0.,   0.,   0., 100.],
       [100.,   0.,   0.,   0.,   0., 100.],
       [100.,   0.,   0.,   0.,   0., 100.],
       [100.,   0.,   0.,   0.,   0., 100.],
       [100., 100., 100., 100., 100., 100.]])

In [216]:
# k = 1 에 따른 value function update
small_grid_world_value_function(epoch = 1)

array([[100., 100., 100., 100., 100., 100.],
       [100.,   0.,  -1.,  -1.,  -1., 100.],
       [100.,  -1.,  -1.,  -1.,  -1., 100.],
       [100.,  -1.,  -1.,  -1.,  -1., 100.],
       [100.,  -1.,  -1.,  -1.,   0., 100.],
       [100., 100., 100., 100., 100., 100.]])

In [217]:
# k = 2 에 따른 value function update
small_grid_world_value_function(epoch = 2)

array([[100.  , 100.  , 100.  , 100.  , 100.  , 100.  ],
       [100.  ,   0.  ,  -1.75,  -2.  ,  -2.  , 100.  ],
       [100.  ,  -1.75,  -2.  ,  -2.  ,  -2.  , 100.  ],
       [100.  ,  -2.  ,  -2.  ,  -2.  ,  -1.75, 100.  ],
       [100.  ,  -2.  ,  -2.  ,  -1.75,   0.  , 100.  ],
       [100.  , 100.  , 100.  , 100.  , 100.  , 100.  ]])

In [218]:
# k = 3 에 따른 value function update
small_grid_world_value_function(epoch = 3)

array([[100.   , 100.   , 100.   , 100.   , 100.   , 100.   ],
       [100.   ,   0.   ,  -2.438,  -2.938,  -3.   , 100.   ],
       [100.   ,  -2.438,  -2.875,  -3.   ,  -2.938, 100.   ],
       [100.   ,  -2.938,  -3.   ,  -2.875,  -2.438, 100.   ],
       [100.   ,  -3.   ,  -2.938,  -2.438,   0.   , 100.   ],
       [100.   , 100.   , 100.   , 100.   , 100.   , 100.   ]])

In [219]:
# k = 4 에 따른 value function update
small_grid_world_value_function(epoch = 4)

array([[100.   , 100.   , 100.   , 100.   , 100.   , 100.   ],
       [100.   ,   0.   ,  -3.063,  -3.844,  -3.969, 100.   ],
       [100.   ,  -3.063,  -3.719,  -3.907,  -3.844, 100.   ],
       [100.   ,  -3.844,  -3.907,  -3.719,  -3.063, 100.   ],
       [100.   ,  -3.969,  -3.844,  -3.063,   0.   , 100.   ],
       [100.   , 100.   , 100.   , 100.   , 100.   , 100.   ]])

In [220]:
# k = 10 에 따른 value function update
small_grid_world_value_function(epoch = 10)

array([[100.   , 100.   , 100.   , 100.   , 100.   , 100.   ],
       [100.   ,   0.   ,  -6.138,  -8.352,  -8.968, 100.   ],
       [100.   ,  -6.138,  -7.737,  -8.428,  -8.352, 100.   ],
       [100.   ,  -8.352,  -8.428,  -7.737,  -6.138, 100.   ],
       [100.   ,  -8.968,  -8.352,  -6.138,   0.   , 100.   ],
       [100.   , 100.   , 100.   , 100.   , 100.   , 100.   ]])

In [221]:
# k 에 따른 value function update
small_grid_world_value_function(epoch = 999)

array([[100.   , 100.   , 100.   , 100.   , 100.   , 100.   ],
       [100.   ,   0.   , -13.997, -19.996, -21.996, 100.   ],
       [100.   , -13.997, -17.996, -19.996, -19.996, 100.   ],
       [100.   , -19.996, -19.996, -17.996, -13.997, 100.   ],
       [100.   , -21.996, -19.996, -13.997,   0.   , 100.   ],
       [100.   , 100.   , 100.   , 100.   , 100.   , 100.   ]])

In [222]:
# k 에 따른 value function update
small_grid_world_value_function(epoch = 999)

array([[100.   , 100.   , 100.   , 100.   , 100.   , 100.   ],
       [100.   ,   0.   , -13.997, -19.996, -21.996, 100.   ],
       [100.   , -13.997, -17.996, -19.996, -19.996, 100.   ],
       [100.   , -19.996, -19.996, -17.996, -13.997, 100.   ],
       [100.   , -21.996, -19.996, -13.997,   0.   , 100.   ],
       [100.   , 100.   , 100.   , 100.   , 100.   , 100.   ]])